### ISSUE TITLE
[Testing-utils]: Asset Distribution from swaps

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-utils#6]
**Asset Distribution from swaps**

A function should be developed to swap and distribute test assets by swapping the ETH (BNB, MATIC, AVAX or any other native asset) provided by the ganache test environment (usually around 20 ETH per test account), through a DEX (Uniswap, Sushiswap, Curve, Quickswap, PancakeSwap, etc). Different exchanges (and their contracts) should be mapped by network as well as the most popular assets supported by these DEXes.

**Comment by sajanrajdev** [comment]
Tool to fetch biggest holders: https://github.com/iamdefinitelyahuman/brownie-token-tester/blob/master/brownie_tokens/forked.py#L28-L52

**Comment by SHAKOTN** [comment]
Will split this issue into 2 separate, because implementation can be quite big for each of two items listed

**Comment by sajanrajdev** [comment]
This function is used generate test LP assets from the Curve protocol, it can serve you as a starting point or reference. You will notice that the pool config is passed as an object, for a more general application it might be better to have the necessary configuration passed as individual parameters. Do as you find fit and don't hesitate to ask me if you have question regarding Curve or other protocol's infrastructure:

https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/main/helpers/test/test_utils.py
